- Infrastructure:
    - Seafile:
        icon: seafile.png
        href: http://seafile.iagofernandez.com
        description: Cloud Storage
    - Nginx Proxy Manager:
        icon: nginx-proxy-manager.png
        href: http://192.168.1.200:81
        description: Reverse Proxy Admin
    - Postgres:
        icon: postgresql.png
        href: http://10.8.0.1:5432
        description: Main Database
