- Infraestructura:
    - Router:
        icon: router.png
        href: http://router.lan
        description: Puerta de enlace local
    - Seafile:
        icon: seafile.png
        href: http://seafile.lan
        description: Almacenamiento en la nube
    - Nginx Proxy Manager:
        icon: nginx-proxy-manager.png
        href: http://nginx.lan
        description: Gestor de proxy inverso
    - Postgres:
        icon: postgresql.png
        href: http://raspberry.lan:5432
        description: Base de datos principal
